### ISSUE TITLE
`flagSet` is undefined

### ISSUE THREAD

**Issue by kylecesmat** [Daplie/node-walk#71]
Hello, a bug was just released in `walk@2.3.11`.

This change looks like it isn't represented in github here, but this is a link to the variable in question - https://git.coolaj86.com/coolaj86/fs-walk.js/src/branch/master/lib/node-type-emitter.js#L53

**Comment by wannabesrevenge** [comment]
@kylecesmat The latest code has a fix for this bug.
here is the commit: https://git.coolaj86.com/coolaj86/fs-walk.js/commit/280bfd28aec9b21697f2cdbef90a1fef13d597e8
  
Please close this issue. Thank you!
